cloudprovider: openstack

# Specify nodepool options. Can add multiple node groups, specify etcd, controlplane and worker roles.
nodepools:
- etcd: true
  controlplane: true
  worker: true

  # specify node labels
  labels: {}

  # specify node taints
  taints: {}

  # specify nodepool size
  quantity: 1

  # Pause node pool
  paused: false

  # specify nodepool name
  name: os-nodepool-1

  authUrl: https://engcloud.prv.suse.net:5000/v3
  domainName: ldap_users
  flavorName: m2.medium
  floatingipPool: floating
  imageName: ubuntu-20.04-focal-server-cloudimg
  insecure: true
  netId: 8f6b659b-14b4-48b3-9c61-9c7bafabc04c
  region: CustomRegion
  tenantId: 05394ae447d74bc0b3ed2cca262c9b7c
  username: tferrandiz
