cloudprovider: openstack

authUrl: https://engcloud.prv.suse.net:5000/v3
domainName: ldap_users
flavorName: m2.medium
floatingipPool: floating
imageName: ubuntu-20.04-focal-server-cloudimg
insecure: true
netId: 8f6b659b-14b4-48b3-9c61-9c7bafabc04c
region: CustomRegion
tenantId: 05394ae447d74bc0b3ed2cca262c9b7c
username: tferrandiz
